### ISSUE TITLE
Ollama for LocaModels not working

### ISSUE THREAD

**Issue by spundhan** [enoch3712/ExtractThinker#148]
The sample given in the readme is not working. Below code does not working anymore.

# Load a custom LLM (e.g., Ollama)
llm = LLM('ollama/phi3', api_base='http://localhost:11434')
extractor.load_llm(llm)

**Comment by enoch3712** [comment]
Hello @spundhan! 

It is! The problem is that i forgot to update the documentation! I will use this issue to do that. 

But instead of: 

`llm = LLM("ollama/phi3", "http://localhost:11434")`

Do now: 
```
    os.environ["BASE_URL"] = "http://localhost:11434"

    llm = LLM("ollama/phi3.5:latest")
```

To give you some context there is a discussion to give space to several LLM/Agent components, that will support LiteLLM or Pydantic. Is the reasons of the change

**Comment by spundhan** [comment]
Yes. This worked fine.
