### ISSUE TITLE
cannot import name 'LLM' from partially initialized module 'extract_thinker'

### ISSUE THREAD

**Issue by stkrompton** [enoch3712/ExtractThinker#19]
hello - could this be an issue in my environment or real issue?

ImportError: cannot import name 'LLM' from partially initialized module 'extract_thinker' (most likely due to a circular import) (my-path/ExtractThinker/extract_thinker/__init__.py)??

**Comment by enoch3712** [comment]
Hello,

Nice catch! It was a problem with the init import of the classes. 

instead of:
`from llm import LLM`
use: 
`from extract_thinker.llm import LLM`

So its just a small bug on the import and seems to be fine, but i will try to solve it and push. In the meantime, use the solution above, is just fine

**Comment by enoch3712** [comment]
@stkrompton 

Pushed. v0.0.7 solves the problem. 

Thank you for the heads up. If persists or any bug, please don't hesitate to open a new issue
